### PR TITLE
Testing CSS import

### PR DESCRIPTION
**Pull request by kolibril13**
I just did some investigations about how to import css into ipyreact widgets.
For that, I've used a simple button react app, and tried different approaches.

The notebook in this pr is meant to be testing and debugging notebook and not yet a proper example, that's why I made this a draft pr.

@maartenbreddels : you're very invited to commit directly to this branch if you have ideas how the CSS import can happen. 
image

### CODE REVIEW

**Comment by maartenbreddels** [comment]
I love this btw, by using code to show how you want something to look, like. No ambiguities.

I am not sure this is technically possible, I did some googling on this.. but I'm afraid we have to choose a different solution (unless you can find the tech to do this).

I thought that we could maybe have a list of links to stylesheets, and support similar to AnyWidget, the _css trait.

**Comment by kolibril13** [comment]
Glad you like it! :)

One naive approach would be regex:
```python
import re

str = 'import "./my_style_red.css";'
regex = r'import\s+"([^"]+\.css)"'
matches = re.search(regex, str)
if matches:
    css_file = matches.group(1)
    print(css_file) # outputs "./my_style_red.css"
```
A script similar to this could run for every string containing react components.
And the css_file output can then be loaded as a stylesheet.

It would be such a smooth experience when one could simply take any react code from a code-sandbox  (where one will sometimes find these `import "./my_style_red.css";` lines ) and copy it to ipyreact without any manual css translation.


But the _css trait sounds good!


Maybe  @manzt has ideas how to include css in a native way?


Also, is there currently another alternative to add css to jupyter then
```
%%html
<link rel="stylesheet" href="my_style_blue.css">
```
(that would always require an extra cell)

**Comment by manzt** [comment]
I've avoided CSS imports/modules in anywidget because they are a _bundler_ concept and not a web standard. By default, anywidget doesn't transform the source code, so the code you write must be "loadable" by the browser natively. The `_css` trait is a convenience hook provided by anywidget to load styles on the page, but this mechanism is separate from the JS source which must be ESM.

Although resolving special imports is a nice feature, I am extremely hesitant to add this functionality directly to anywidget. In the end, all bundlers transform code into JS that a browser most understand natively. Therefore, I see anywidget's modules (`export render() { ... }`) as a single compiler target for these tools if one wants to use one. Bundlers are always in flux, and designing around a special bundler (webpack) is exactly why the jupyter widgets ecosystem got so fragmented with the cookiecutter approach.

With that said, [import assertions](https://github.com/tc39/proposal-import-attributes) proposal from TC39 is probably the closest thing to allow CSS imports, but you still need to manually update the DOM stylesheet from JS. I'm exploring ideas to bundle browser standard imports so that multi-file widgets are easier.

**Comment by maartenbreddels** [comment]
> The other challenge is then resolving the captured import `"./my_style_blue.css"` to the file system.

i see a security risk in deployed apps via voila and solara :)

**Comment by kolibril13** [comment]
That sounds reasonable.
I'm looking forward to using _css trait in ipyreact then! 
@maartenbreddels : do you have any plans on when you might be able to implement the new CSS trait feature?
With a proper way to load CSS, I will soon be ready to ship a  jupyter tldraw annotation widget!
Sneak preview: 
image

**Comment by maartenbreddels** [comment]
Do you really need to have it on the widget itself?

I'm guessing this CSS is not just for this widget right? If so, maybe use https://solara.dev/api/style ?

**Comment by maartenbreddels** [comment]
Yeah, that would also work!

**Comment by maartenbreddels** [comment]
FYI: you can not calling a HTML function, but you create a displayable HTML object. Since it is the last expression of the notebook cell, it gets automatically "displayed". Calling display(...) has the same effect. So if you don't have it as a last expression, you can call `display(HTML(...))`.

**Comment by kolibril13** [comment]
Nice!
When I have file `x.py`
```python
from IPython.display import HTML 
from IPython.display import display
from pathlib import Path
css_rules = Path('styles_orange.css').read_text()
display(HTML('<style>' + css_rules + '</style>'))
print("Hello!")
``` 
 and import the file the first time, it works!
image

but when I run the import cell a second time, then the import is not executed again, and the output of the import cell is overwritten by an empty output, and therefore the css is also lost again.
image

**Comment by maartenbreddels** [comment]
Yes, that is because you overwrite the output :)

**Comment by manzt** [comment]
Just to chime in, CSS is really tricky because similar to JS before ESM – stylesheets are all loaded globally. This is why frontend developers usually use something like[postcss](https://github.com/postcss/postcss) to process CSS imports as a part of their build. This means that when you include something like:

```js
import "./foo.css";

export function App() {
  return <h1 className="foo">Hello, world</h1>
}
```

the resulting "build" will include `.css` file and `.js` where the class name "foo" has been transformed to something unique. There are _many_ ways to load CSS from JavaScript, and we settled on opinionated pattern in anywidget for convenience.

**Pull request closed without merging**
