### PR TITLE
JupyterLite-Part5

### PR DESCRIPTION
**Pull request by kolibril13**
This setting will prevent JupyterLite from caching content, as discussed in:
https://github.com/jupyterlite/jupyterlite/issues/1067#issuecomment-1550405195
Benefit:
Users will always see the latest JupyterLite content, and closing the JupyterLite website will discard all changes.

### CODE REVIEW

**Comment by kolibril13** [comment]
@maartenbreddels : This is ready to be merged.

**Comment by maartenbreddels** [comment]
Can you rebase to master?

**Comment by kolibril13** [comment]
I just merged the latest master by pressing the sync button:

image

I think this should be fine, when you quash merging this pr, right?

**Comment by maartenbreddels** [comment]
Indeed, but if you see an option to rebase, even better. I don’t see this on my mobile btw. 
anyway, green, thanks!

**Pull request merged**
