### PR TITLE
feat: events: call python methods from frontend

### PR DESCRIPTION
**Pull request by maartenbreddels**
We have a similar feature in ipyvue. Would be great if we can agree on this API with anywidget. cc @manzt

### CODE REVIEW

**Review by kolibril13 — APPROVED** [review]
>  @kolibril13 what do you think? Should we merge this?

I think merging this will be a great addition to ipyreact!
I was testing this branch locally, and the python calls work as they should.

**Comment by kolibril13** [comment]
How about a v0.3.0 release to ship this feature? :)

**Comment by maartenbreddels** [comment]
I want to have the set_ change in. I think for backwards compatibility we keep both on_ and set_, what do you think? But it requires some docs changes as well.

**Comment by kolibril13** [comment]
Having `_set` in the next release sounds great!
I think there are only very few people using ipyreact right now, so backwards compatibility is not too important in my opinion.
Having both options available might cause more confusion than convenience.
Another idea would be to have a deprecation warning when one tries to use on_.

**Comment by maartenbreddels** [comment]
See https://github.com/widgetti/ipyreact/pull/27

Do you have time to pick up the docs/example changes?

Btw, I hate breakage, even if 2 people use it :)

**Comment by kolibril13** [comment]
Yep, just changed all the examples, and I think we are at least 3 people!  :)

**Comment by maartenbreddels** [comment]
0.3 is out 🥳

**Pull request merged**
